import React, { useState, useEffect, useRef } from 'react'
import { generateDocs } from '../utils/aiApi'
import html2pdf from 'html2pdf.js'

export default function DocsPage() {
  const [connected, setConnected] = useState(false)
  const [addr, setAddr] = useState('')
  const [projectName, setProjectName] = useState('')
  const [docType, setDocType] = useState('Whitepaper')
  const [description, setDescription] = useState('')
  const [tokenomics, setTokenomics] = useState('')
  const [generating, setGenerating] = useState(false)
  const [generatedContent, setGeneratedContent] = useState('')
  const [error, setError] = useState('')
  const pdfRef = useRef(null)

  const docTypes = ['Whitepaper', 'Technical Docs', 'Litepaper']

  useEffect(() => {
    if (window.ethereum) {
      window.ethereum.request({ method: 'eth_accounts' }).then(accounts => {
        if (accounts.length > 0) {
          setAddr(accounts[0])
          setConnected(true)
        }
      })
    }
  }, [])

  const connect = async () => {
    if (window.ethereum) {
      try {
        const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' })
        if (accounts.length > 0) {
          setAddr(accounts[0])
          setConnected(true)
        }
      } catch (e) {
        alert('Please install MetaMask')
      }
    } else {
      alert('Please install MetaMask')
    }
  }

  const disconnect = () => {
    setConnected(false)
    setAddr('')
  }

  const generate = async () => {
    if (!connected) {
      connect()
      return
    }
    if (!projectName) {
      alert('Please enter project name')
      return
    }

    setGenerating(true)
    setError('')
    setGeneratedContent('')

    try {
      const content = await generateDocs(projectName, docType)
      setGeneratedContent(content)
    } catch (err) {
      setError('Failed to generate: ' + err.message)
    } finally {
      setGenerating(false)
    }
  }

  const downloadPDF = () => {
    if (!generatedContent || !pdfRef.current) return

    const element = pdfRef.current
    const opt = {
      margin: 15,
      filename: `${projectName || 'Document'}_${docType}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    }

    html2pdf().set(opt).from(element).save()
  }

  const downloadMarkdown = () => {
    if (!generatedContent) return

    const mdContent = `# ${projectName || 'Project'} ${docType}\n\n${generatedContent}\n\n---\nGenerated by AI Creator Hub • ${new Date().toLocaleDateString()}`
    const blob = new Blob([mdContent], { type: 'text/markdown' })
    const link = document.createElement('a')
    link.download = `${projectName || 'Document'}_${docType}.md`
    link.href = URL.createObjectURL(blob)
    link.click()
  }

  return (
    React.createElement('div', {style: {minHeight: '100vh', background: '#050508', color: 'white', position: 'relative'}},
      React.createElement('div', {style: {position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'url(bg.jpg) center/cover fixed', zIndex: 0}}),
      React.createElement('div', {style: {position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0, 0, 0, 0.85)', zIndex: 1}}),
      React.createElement('div', {style: {position: 'relative', zIndex: 2, maxWidth: '900px', margin: '0 auto', padding: '0 40px'}},
        React.createElement('header', {style: {display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '30px 0'}},
          React.createElement('div', {style: {fontSize: '1.2rem', fontWeight: 500, letterSpacing: '1px'}}, 'AI Creator Hub'),
          React.createElement('button', {
            onClick: () => window.location.hash = '',
            style: {padding: '8px 16px', background: 'rgba(255,255,255,0.1)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: '6px', color: 'white', cursor: 'pointer', fontSize: '0.85rem'}
          }, 'Home')
        ),
        React.createElement('h1', {style: {fontSize: '2.5rem', fontWeight: 600, marginBottom: '8px', letterSpacing: '-0.5px'}}, 'Create Docs'),
        React.createElement('p', {style: {color: '#888', marginBottom: '30px', fontSize: '1.11rem'}}, 'AI-powered documentation generation'),
        
        React.createElement('div', {style: {display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '20px', background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.05)', marginBottom: '30px'}},
          React.createElement('div', {style: {display: 'flex', alignItems: 'center', gap: '12px'}},
            React.createElement('div', {style: {width: '10px', height: '10px', background: connected ? '#00ff88' : '#ff4444', borderRadius: '50%'}}),
            React.createElement('div', null,
              React.createElement('div', {style: {fontSize: '0.95rem', color: connected ? '#00ff88' : 'white'}}, connected ? addr.slice(0, 6) + '...' + addr.slice(-4) : 'No Wallet'),
              React.createElement('div', {style: {fontSize: '0.85rem', color: '#888'}}, connected ? '' : 'Connect wallet first')
            )
          ),
          React.createElement('button', {
            onClick: connected ? disconnect : connect,
            style: {padding: '12px 24px', fontSize: '0.9rem', fontWeight: 500, borderRadius: '8px', background: connected ? 'transparent' : 'linear-gradient(135deg, #ff00ff, #00ffff)', color: connected ? 'white' : '#050508', border: connected ? '1px solid rgba(255,255,255,0.2)' : 'none'}
          }, connected ? 'Disconnect' : 'Connect Wallet')
        ),

        React.createElement('div', {style: {background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.05)', padding: '40px', marginBottom: '40px'}},
          React.createElement('div', {style: {marginBottom: '30px'}},
            React.createElement('div', {style: {marginBottom: '20px'}},
              React.createElement('label', {style: {display: 'block', fontSize: '0.9rem', color: '#888', marginBottom: '8px'}}, 'Project Name'),
              React.createElement('input', {
                type: 'text',
                placeholder: 'e.g. DeFi Protocol',
                value: projectName,
                onChange: e => setProjectName(e.target.value),
                style: {width: '100%', padding: '14px 16px', background: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.1)', color: 'white', fontSize: '1rem', borderRadius: '8px'}
              })
            ),
            React.createElement('div', {style: {marginBottom: '20px'}},
              React.createElement('label', {style: {display: 'block', fontSize: '0.9rem', color: '#888', marginBottom: '8px'}}, 'Document Type'),
              React.createElement('select', {
                value: docType,
                onChange: e => setDocType(e.target.value),
                style: {width: '100%', padding: '14px 16px', background: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.1)', color: 'white', fontSize: '1rem', borderRadius: '8px'}
              },
                React.createElement('option', {value: 'Whitepaper'}, 'Whitepaper'),
                React.createElement('option', {value: 'Technical Docs'}, 'Technical Docs'),
                React.createElement('option', {value: 'Litepaper'}, 'Litepaper')
              )
            ),
            React.createElement('div', {style: {marginBottom: '20px'}},
              React.createElement('label', {style: {display: 'block', fontSize: '0.9rem', color: '#888', marginBottom: '8px'}}, 'Description'),
              React.createElement('textarea', {
                placeholder: 'Describe your project...',
                value: description,
                onChange: e => setDescription(e.target.value),
                style: {width: '100%', padding: '14px 16px', background: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.1)', color: 'white', fontSize: '1rem', borderRadius: '8px', minHeight: '100px', resize: 'vertical', fontFamily: 'inherit'}
              })
            ),
            React.createElement('div', {style: {marginBottom: '20px'}},
              React.createElement('label', {style: {display: 'block', fontSize: '0.9rem', color: '#888', marginBottom: '8px'}}, 'Tokenomics'),
              React.createElement('textarea', {
                placeholder: 'Token distribution, supply, utility...',
                value: tokenomics,
                onChange: e => setTokenomics(e.target.value),
                style: {width: '100%', padding: '14px 16px', background: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.1)', color: 'white', fontSize: '1rem', borderRadius: '8px', minHeight: '100px', resize: 'vertical', fontFamily: 'inherit'}
              })
            )
          ),
          React.createElement('button', {
            onClick: generate,
            disabled: generating,
            style: {display: 'inline-flex', alignItems: 'center', gap: '10px', padding: '16px 32px', fontSize: '1rem', fontWeight: 500, border: 'none', borderRadius: '8px', background: 'linear-gradient(135deg, #ff00ff, #00ffff)', color: '#050508', opacity: generating ? 0.5 : 1, marginRight: '12px'}
          }, generating ? 'Generating...' : 'Generate Docs'),
          generatedContent && React.createElement('button', {
            onClick: downloadPDF,
            style: {padding: '16px 32px', fontSize: '1rem', fontWeight: 500, border: 'none', borderRadius: '8px', background: 'transparent', color: 'white', border: '1px solid rgba(255,255,255,0.2)', marginRight: '12px'}
          }, 'PDF'),
          generatedContent && React.createElement('button', {
            onClick: downloadMarkdown,
            style: {padding: '16px 32px', fontSize: '1rem', fontWeight: 500, border: 'none', borderRadius: '8px', background: 'transparent', color: 'white', border: '1px solid rgba(255,255,255,0.2)'}
          }, 'Markdown'),
          error && React.createElement('div', {style: {marginTop: '20px', padding: '16px', background: 'rgba(255,0,0,0.1)', borderRadius: '8px', color: '#ff4444'}}, error)
        ),

        generatedContent && React.createElement('div', {style: {background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.05)', padding: '30px', marginBottom: '40px'}},
          React.createElement('h3', {style: {fontSize: '1.1rem', fontWeight: 600, marginBottom: '20px'}}, '// Document Preview'),
          React.createElement('div', {ref: pdfRef, style: {background: 'white', color: '#333', borderRadius: '8px', padding: '24px', minHeight: '400px', fontFamily: 'Georgia, serif'}},
            React.createElement('div', {style: {textAlign: 'center', marginBottom: '30px', paddingBottom: '20px', borderBottom: '2px solid #1a1a2e'}},
              React.createElement('h1', {style: {color: '#1a1a2e', fontSize: '1.3rem', marginBottom: '10px'}}, projectName),
              React.createElement('p', {style: {color: '#666', fontSize: '0.9rem', fontStyle: 'italic'}}, docType)
            ),
            React.createElement('div', {style: {whiteSpace: 'pre-wrap', fontSize: '0.85rem', lineHeight: 1.8, color: '#333'}}, generatedContent),
            React.createElement('div', {style: {marginTop: '40px', paddingTop: '20px', borderTop: '1px solid #eee', fontSize: '0.75rem', color: '#999', textAlign: 'center'}}, 'Generated by AI Creator Hub • ' + new Date().toLocaleDateString())
          )
        ),

        React.createElement('div', {style: {display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '30px', padding: '40px 0', borderTop: '1px solid rgba(255,255,255,0.1)'}},
          React.createElement('div', {style: {textAlign: 'center'}},
            React.createElement('div', {style: {fontSize: '1.8rem', marginBottom: '10px'}}, '📄'),
            React.createElement('div', {style: {fontSize: '1rem', fontWeight: 500, marginBottom: '6px'}}, 'Professional'),
            React.createElement('div', {style: {fontSize: '0.9rem', color: '#888'}}, 'Well-structured content')
          ),
          React.createElement('div', {style: {textAlign: 'center'}},
            React.createElement('div', {style: {fontSize: '1.8rem', marginBottom: '10px'}}, '🔒'),
            React.createElement('div', {style: {fontSize: '1rem', fontWeight: 500, marginBottom: '6px'}}, 'Verified'),
            React.createElement('div', {style: {fontSize: '0.9rem', color: '#888'}}, 'Open source standard')
          ),
          React.createElement('div', {style: {textAlign: 'center'}},
            React.createElement('div', {style: {fontSize: '1.8rem', marginBottom: '10px'}}, '⚡'),
            React.createElement('div', {style: {fontSize: '1rem', fontWeight: 500, marginBottom: '6px'}}, 'Instant'),
            React.createElement('div', {style: {fontSize: '0.9rem', color: '#888'}}, 'Generate in seconds')
          )
        ),

        React.createElement('footer', {style: {padding: '30px 0', borderTop: '1px solid rgba(255,255,255,0.1)', textAlign: 'center'}},
          React.createElement('p', {style: {color: '#888', fontSize: '0.85rem'}}, 'AI Creator Hub © 2024')
        )
      )
    )
  )
}
